global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
scrape_configs:
  - job_name: "nginx"
    static_configs:
      - targets: ['192.168.137.248:9113']
        labels:
          service: 'basic_status'
      - targets: ['192.168.137.248:9114']
        labels:
          service: 'nginx_log'
