{
 "title": "nginx",
 "tags": [
  "NGINX",
  "Load Balancer"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "nginx accepted/handled",
   "type": "timeseries",
   "description": "Accepted : The total number of accepted client connections.\n\n\nHandled : The total number of handled connections. Generally, the parameter value is the same as accepts unless some resource limits have been reached (for example, the worker_connections limit).\n\n\nworker connection : Sets the maximum number of simultaneous connections that can be opened by a worker process.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "irate(nginx_connections_handled[1m])",
     "legendFormat": "handled"
    }
   ]
  },
  {
   "title": "nginx connection",
   "type": "timeseries",
   "description": "Active : The current number of active client connections including Waiting connections.\n\nReading : The current number of connections where nginx is reading the request header.\n\nWaiting : The current number of idle client connections waiting for a request.\n\nWriting : The current number of connections where nginx is writing the response back to the client.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "active" },
    { "expr": "nginx_connections_reading", "legendFormat": "reading" },
    { "expr": "nginx_connections_waiting", "legendFormat": "waiting" },
    { "expr": "nginx_connections_writing", "legendFormat": "writing" }
   ]
  },
  {
   "title": "response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nginx_http_response_time_seconds_sum{status=~\"[0-9]{3}\"}[1m])",
     "legendFormat": "{{method}} : {{status}}"
    }
   ]
  },
  {
   "title": "request total (24h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[24h])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "response count total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(nginx_http_response_count_total{status=~\"[0-9]{3}\"}[1m]) > 0",
     "legendFormat": "{{method}} :  {{status}}"
    }
   ]
  },
  {
   "title": "nginx parse log errors total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(nginx_parse_errors_total[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "upstream connect time seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nginx_http_upstream_connect_time_seconds_sum{status=~\"[0-9]{3}\"}[1m])",
     "legendFormat": "{{method}} :  {{status}}"
    }
   ]
  },
  {
   "title": "upstream time seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nginx_http_upstream_time_seconds_sum{status=~\"[0-9]{3}\"}[1m])",
     "legendFormat": "{{method}} :  {{status}}"
    }
   ]
  }
 ]
}